import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-offwhite text-offblack py-4 shadow-lg">
          <div className="flex justify-between items-center">
            <div className="flex ml-4 pl-10 ">
              <Link href="/" className="flex justify-center items-center">
                <span
                  role="img"
                  aria-label="turtle"
                  className="text-4xl flex items-center space-x-4"
                >
                  🐢
                </span>
                <h1 className="text-2xl font-bold cursor-pointer ml-2">
                  Tortoise Investing
                </h1>
              </Link>
            </div>
            <div className="flex mr-4 pr-20">
              <Link
                href="/stock"
                className="text-2xl flex items-center text-offblack hover:underline mr-4 font-sans"
              >
                Simulate
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
